# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Users: bcrypt

    providers:
        users:
            entity:
                class: AppBundle\Entity\Users
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/(connection|api)

        admin:
            pattern: ^/
            provider: users
            form_login:
                login_path: app_connection
                check_path: app_login_check
                default_target_path: app_home
                use_referer: true
            logout:
                path: app_logout
                target: app_connection
